           
diagram_fact(align, cell_100, "left").
diagram_fact(align, cell_105, "left").
diagram_fact(align, cell_110, "left").
diagram_fact(align, cell_14, "left").
diagram_fact(align, cell_18, "left").
diagram_fact(align, cell_23, "left").
diagram_fact(align, cell_28, "left").
diagram_fact(align, cell_33, "left").
diagram_fact(align, cell_38, "left").
diagram_fact(align, cell_41, "left").
diagram_fact(align, cell_47, "left").
diagram_fact(align, cell_50, "left").
diagram_fact(align, cell_55, "left").
diagram_fact(align, cell_60, "left").
diagram_fact(align, cell_65, "left").
diagram_fact(align, cell_70, "left").
diagram_fact(align, cell_75, "left").
diagram_fact(align, cell_80, "left").
diagram_fact(align, cell_85, "left").
diagram_fact(align, cell_9, "left").
diagram_fact(align, cell_90, "left").
diagram_fact(align, cell_95, "left").
diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_100, "geometry").
diagram_fact(as, cell_101, "geometry").
diagram_fact(as, cell_102, "geometry").
diagram_fact(as, cell_103, "geometry").
diagram_fact(as, cell_104, "geometry").
diagram_fact(as, cell_105, "geometry").
diagram_fact(as, cell_106, "geometry").
diagram_fact(as, cell_107, "geometry").
diagram_fact(as, cell_108, "geometry").
diagram_fact(as, cell_109, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_110, "geometry").
diagram_fact(as, cell_111, "geometry").
diagram_fact(as, cell_112, "geometry").
diagram_fact(as, cell_113, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_17, "geometry").
diagram_fact(as, cell_18, "geometry").
diagram_fact(as, cell_19, "geometry").
diagram_fact(as, cell_20, "geometry").
diagram_fact(as, cell_21, "geometry").
diagram_fact(as, cell_22, "geometry").
diagram_fact(as, cell_23, "geometry").
diagram_fact(as, cell_24, "geometry").
diagram_fact(as, cell_25, "geometry").
diagram_fact(as, cell_26, "geometry").
diagram_fact(as, cell_27, "geometry").
diagram_fact(as, cell_28, "geometry").
diagram_fact(as, cell_29, "geometry").
diagram_fact(as, cell_30, "geometry").
diagram_fact(as, cell_31, "geometry").
diagram_fact(as, cell_32, "geometry").
diagram_fact(as, cell_33, "geometry").
diagram_fact(as, cell_34, "geometry").
diagram_fact(as, cell_35, "geometry").
diagram_fact(as, cell_36, "geometry").
diagram_fact(as, cell_37, "geometry").
diagram_fact(as, cell_38, "geometry").
diagram_fact(as, cell_39, "geometry").
diagram_fact(as, cell_40, "geometry").
diagram_fact(as, cell_41, "geometry").
diagram_fact(as, cell_42, "geometry").
diagram_fact(as, cell_43, "geometry").
diagram_fact(as, cell_44, "geometry").
diagram_fact(as, cell_45, "geometry").
diagram_fact(as, cell_46, "geometry").
diagram_fact(as, cell_47, "geometry").
diagram_fact(as, cell_48, "geometry").
diagram_fact(as, cell_49, "geometry").
diagram_fact(as, cell_50, "geometry").
diagram_fact(as, cell_51, "geometry").
diagram_fact(as, cell_52, "geometry").
diagram_fact(as, cell_53, "geometry").
diagram_fact(as, cell_54, "geometry").
diagram_fact(as, cell_55, "geometry").
diagram_fact(as, cell_56, "geometry").
diagram_fact(as, cell_57, "geometry").
diagram_fact(as, cell_58, "geometry").
diagram_fact(as, cell_59, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_60, "geometry").
diagram_fact(as, cell_61, "geometry").
diagram_fact(as, cell_62, "geometry").
diagram_fact(as, cell_63, "geometry").
diagram_fact(as, cell_64, "geometry").
diagram_fact(as, cell_65, "geometry").
diagram_fact(as, cell_66, "geometry").
diagram_fact(as, cell_67, "geometry").
diagram_fact(as, cell_68, "geometry").
diagram_fact(as, cell_69, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_70, "geometry").
diagram_fact(as, cell_71, "geometry").
diagram_fact(as, cell_72, "geometry").
diagram_fact(as, cell_73, "geometry").
diagram_fact(as, cell_74, "geometry").
diagram_fact(as, cell_75, "geometry").
diagram_fact(as, cell_76, "geometry").
diagram_fact(as, cell_77, "geometry").
diagram_fact(as, cell_78, "geometry").
diagram_fact(as, cell_79, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_80, "geometry").
diagram_fact(as, cell_81, "geometry").
diagram_fact(as, cell_82, "geometry").
diagram_fact(as, cell_83, "geometry").
diagram_fact(as, cell_84, "geometry").
diagram_fact(as, cell_85, "geometry").
diagram_fact(as, cell_86, "geometry").
diagram_fact(as, cell_87, "geometry").
diagram_fact(as, cell_88, "geometry").
diagram_fact(as, cell_89, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(as, cell_90, "geometry").
diagram_fact(as, cell_91, "geometry").
diagram_fact(as, cell_92, "geometry").
diagram_fact(as, cell_93, "geometry").
diagram_fact(as, cell_94, "geometry").
diagram_fact(as, cell_95, "geometry").
diagram_fact(as, cell_96, "geometry").
diagram_fact(as, cell_97, "geometry").
diagram_fact(as, cell_98, "geometry").
diagram_fact(as, cell_99, "geometry").
diagram_fact(aspect, cell_102, "fixed").
diagram_fact(aspect, cell_103, "fixed").
diagram_fact(aspect, cell_107, "fixed").
diagram_fact(aspect, cell_108, "fixed").
diagram_fact(aspect, cell_11, "fixed").
diagram_fact(aspect, cell_112, "fixed").
diagram_fact(aspect, cell_113, "fixed").
diagram_fact(aspect, cell_12, "fixed").
diagram_fact(aspect, cell_16, "fixed").
diagram_fact(aspect, cell_17, "fixed").
diagram_fact(aspect, cell_20, "fixed").
diagram_fact(aspect, cell_21, "fixed").
diagram_fact(aspect, cell_25, "fixed").
diagram_fact(aspect, cell_26, "fixed").
diagram_fact(aspect, cell_30, "fixed").
diagram_fact(aspect, cell_31, "fixed").
diagram_fact(aspect, cell_35, "fixed").
diagram_fact(aspect, cell_36, "fixed").
diagram_fact(aspect, cell_39, "fixed").
diagram_fact(aspect, cell_43, "fixed").
diagram_fact(aspect, cell_45, "fixed").
diagram_fact(aspect, cell_48, "fixed").
diagram_fact(aspect, cell_51, "fixed").
diagram_fact(aspect, cell_53, "fixed").
diagram_fact(aspect, cell_57, "fixed").
diagram_fact(aspect, cell_58, "fixed").
diagram_fact(aspect, cell_62, "fixed").
diagram_fact(aspect, cell_63, "fixed").
diagram_fact(aspect, cell_67, "fixed").
diagram_fact(aspect, cell_68, "fixed").
diagram_fact(aspect, cell_72, "fixed").
diagram_fact(aspect, cell_73, "fixed").
diagram_fact(aspect, cell_77, "fixed").
diagram_fact(aspect, cell_78, "fixed").
diagram_fact(aspect, cell_82, "fixed").
diagram_fact(aspect, cell_83, "fixed").
diagram_fact(aspect, cell_87, "fixed").
diagram_fact(aspect, cell_88, "fixed").
diagram_fact(aspect, cell_92, "fixed").
diagram_fact(aspect, cell_93, "fixed").
diagram_fact(aspect, cell_97, "fixed").
diagram_fact(aspect, cell_98, "fixed").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_100, "").
diagram_fact(cell, cell_101, "").
diagram_fact(cell, cell_102, "").
diagram_fact(cell, cell_103, "").
diagram_fact(cell, cell_104, "").
diagram_fact(cell, cell_105, "").
diagram_fact(cell, cell_106, "").
diagram_fact(cell, cell_107, "").
diagram_fact(cell, cell_108, "").
diagram_fact(cell, cell_109, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_110, "").
diagram_fact(cell, cell_111, "").
diagram_fact(cell, cell_112, "").
diagram_fact(cell, cell_113, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_17, "").
diagram_fact(cell, cell_18, "").
diagram_fact(cell, cell_19, "").
diagram_fact(cell, cell_20, "").
diagram_fact(cell, cell_21, "").
diagram_fact(cell, cell_22, "").
diagram_fact(cell, cell_23, "").
diagram_fact(cell, cell_24, "").
diagram_fact(cell, cell_25, "").
diagram_fact(cell, cell_26, "").
diagram_fact(cell, cell_27, "").
diagram_fact(cell, cell_28, "").
diagram_fact(cell, cell_29, "").
diagram_fact(cell, cell_30, "").
diagram_fact(cell, cell_31, "").
diagram_fact(cell, cell_32, "").
diagram_fact(cell, cell_33, "").
diagram_fact(cell, cell_34, "").
diagram_fact(cell, cell_35, "").
diagram_fact(cell, cell_36, "").
diagram_fact(cell, cell_37, "").
diagram_fact(cell, cell_38, "").
diagram_fact(cell, cell_39, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_40, "").
diagram_fact(cell, cell_41, "").
diagram_fact(cell, cell_42, "").
diagram_fact(cell, cell_43, "").
diagram_fact(cell, cell_44, "").
diagram_fact(cell, cell_45, "").
diagram_fact(cell, cell_46, "").
diagram_fact(cell, cell_47, "").
diagram_fact(cell, cell_48, "").
diagram_fact(cell, cell_49, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_50, "").
diagram_fact(cell, cell_51, "").
diagram_fact(cell, cell_52, "").
diagram_fact(cell, cell_53, "").
diagram_fact(cell, cell_54, "").
diagram_fact(cell, cell_55, "").
diagram_fact(cell, cell_56, "").
diagram_fact(cell, cell_57, "").
diagram_fact(cell, cell_58, "").
diagram_fact(cell, cell_59, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_60, "").
diagram_fact(cell, cell_61, "").
diagram_fact(cell, cell_62, "").
diagram_fact(cell, cell_63, "").
diagram_fact(cell, cell_64, "").
diagram_fact(cell, cell_65, "").
diagram_fact(cell, cell_66, "").
diagram_fact(cell, cell_67, "").
diagram_fact(cell, cell_68, "").
diagram_fact(cell, cell_69, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_70, "").
diagram_fact(cell, cell_71, "").
diagram_fact(cell, cell_72, "").
diagram_fact(cell, cell_73, "").
diagram_fact(cell, cell_74, "").
diagram_fact(cell, cell_75, "").
diagram_fact(cell, cell_76, "").
diagram_fact(cell, cell_77, "").
diagram_fact(cell, cell_78, "").
diagram_fact(cell, cell_79, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_80, "").
diagram_fact(cell, cell_81, "").
diagram_fact(cell, cell_82, "").
diagram_fact(cell, cell_83, "").
diagram_fact(cell, cell_84, "").
diagram_fact(cell, cell_85, "").
diagram_fact(cell, cell_86, "").
diagram_fact(cell, cell_87, "").
diagram_fact(cell, cell_88, "").
diagram_fact(cell, cell_89, "").
diagram_fact(cell, cell_9, "").
diagram_fact(cell, cell_90, "").
diagram_fact(cell, cell_91, "").
diagram_fact(cell, cell_92, "").
diagram_fact(cell, cell_93, "").
diagram_fact(cell, cell_94, "").
diagram_fact(cell, cell_95, "").
diagram_fact(cell, cell_96, "").
diagram_fact(cell, cell_97, "").
diagram_fact(cell, cell_98, "").
diagram_fact(cell, cell_99, "").
diagram_fact(diagram, diagram_1, "").
diagram_fact(edge, cell_10, 1).
diagram_fact(edge, cell_101, 1).
diagram_fact(edge, cell_106, 1).
diagram_fact(edge, cell_111, 1).
diagram_fact(edge, cell_15, 1).
diagram_fact(edge, cell_19, 1).
diagram_fact(edge, cell_24, 1).
diagram_fact(edge, cell_29, 1).
diagram_fact(edge, cell_34, 1).
diagram_fact(edge, cell_42, 1).
diagram_fact(edge, cell_44, 1).
diagram_fact(edge, cell_52, 1).
diagram_fact(edge, cell_56, 1).
diagram_fact(edge, cell_61, 1).
diagram_fact(edge, cell_66, 1).
diagram_fact(edge, cell_71, 1).
diagram_fact(edge, cell_76, 1).
diagram_fact(edge, cell_81, 1).
diagram_fact(edge, cell_86, 1).
diagram_fact(edge, cell_91, 1).
diagram_fact(edge, cell_96, 1).
diagram_fact(edgeStyle, cell_10, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_101, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_106, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_111, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_15, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_19, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_24, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_29, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_34, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_42, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_44, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_52, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_56, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_61, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_66, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_71, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_76, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_81, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_86, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_91, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_96, "orthogonalEdgeStyle").
diagram_fact(entryDx, cell_10, 0).
diagram_fact(entryDx, cell_101, 0).
diagram_fact(entryDx, cell_106, 0).
diagram_fact(entryDx, cell_111, 0).
diagram_fact(entryDx, cell_15, 0).
diagram_fact(entryDx, cell_19, 0).
diagram_fact(entryDx, cell_24, 0).
diagram_fact(entryDx, cell_29, 0).
diagram_fact(entryDx, cell_42, 0).
diagram_fact(entryDx, cell_44, 0).
diagram_fact(entryDx, cell_52, 0).
diagram_fact(entryDx, cell_56, 0).
diagram_fact(entryDx, cell_61, 0).
diagram_fact(entryDx, cell_66, 0).
diagram_fact(entryDx, cell_71, 0).
diagram_fact(entryDx, cell_76, 0).
diagram_fact(entryDx, cell_81, 0).
diagram_fact(entryDx, cell_86, 0).
diagram_fact(entryDx, cell_91, 0).
diagram_fact(entryDx, cell_96, 0).
diagram_fact(entryDy, cell_10, 0).
diagram_fact(entryDy, cell_101, 0).
diagram_fact(entryDy, cell_106, 0).
diagram_fact(entryDy, cell_111, 0).
diagram_fact(entryDy, cell_15, 0).
diagram_fact(entryDy, cell_19, 0).
diagram_fact(entryDy, cell_24, 0).
diagram_fact(entryDy, cell_29, 0).
diagram_fact(entryDy, cell_42, 0).
diagram_fact(entryDy, cell_44, 0).
diagram_fact(entryDy, cell_52, 0).
diagram_fact(entryDy, cell_56, 0).
diagram_fact(entryDy, cell_61, 0).
diagram_fact(entryDy, cell_66, 0).
diagram_fact(entryDy, cell_71, 0).
diagram_fact(entryDy, cell_76, 0).
diagram_fact(entryDy, cell_81, 0).
diagram_fact(entryDy, cell_86, 0).
diagram_fact(entryDy, cell_91, 0).
diagram_fact(entryDy, cell_96, 0).
diagram_fact(entryX, cell_10, 0).
diagram_fact(entryX, cell_101, 0).
diagram_fact(entryX, cell_106, 0).
diagram_fact(entryX, cell_111, 0).
diagram_fact(entryX, cell_15, 0).
diagram_fact(entryX, cell_19, 0).
diagram_fact(entryX, cell_24, 0).
diagram_fact(entryX, cell_29, 0).
diagram_fact(entryX, cell_42, 0).
diagram_fact(entryX, cell_44, 0).
diagram_fact(entryX, cell_52, 0).
diagram_fact(entryX, cell_56, 0).
diagram_fact(entryX, cell_61, 0).
diagram_fact(entryX, cell_66, 0).
diagram_fact(entryX, cell_71, 0).
diagram_fact(entryX, cell_76, 0).
diagram_fact(entryX, cell_81, 0).
diagram_fact(entryX, cell_86, 0).
diagram_fact(entryX, cell_91, 0).
diagram_fact(entryX, cell_96, 0).
diagram_fact(entryY, cell_10, 0.5).
diagram_fact(entryY, cell_101, 0.5).
diagram_fact(entryY, cell_106, 0.5).
diagram_fact(entryY, cell_111, 0.5).
diagram_fact(entryY, cell_15, 0.5).
diagram_fact(entryY, cell_19, 0.5).
diagram_fact(entryY, cell_24, 0.5).
diagram_fact(entryY, cell_29, 0.5).
diagram_fact(entryY, cell_42, 0.5).
diagram_fact(entryY, cell_44, 0.5).
diagram_fact(entryY, cell_52, 0.5).
diagram_fact(entryY, cell_56, 0.5).
diagram_fact(entryY, cell_61, 0.5).
diagram_fact(entryY, cell_66, 0.5).
diagram_fact(entryY, cell_71, 0.5).
diagram_fact(entryY, cell_76, 0.5).
diagram_fact(entryY, cell_81, 0.5).
diagram_fact(entryY, cell_86, 0.5).
diagram_fact(entryY, cell_91, 0.5).
diagram_fact(entryY, cell_96, 0.5).
diagram_fact(exitDx, cell_10, 0).
diagram_fact(exitDx, cell_101, 0).
diagram_fact(exitDx, cell_106, 0).
diagram_fact(exitDx, cell_111, 0).
diagram_fact(exitDx, cell_15, 0).
diagram_fact(exitDx, cell_19, 0).
diagram_fact(exitDx, cell_24, 0).
diagram_fact(exitDx, cell_29, 0).
diagram_fact(exitDx, cell_34, 0).
diagram_fact(exitDx, cell_42, 0).
diagram_fact(exitDx, cell_44, 0).
diagram_fact(exitDx, cell_52, 0).
diagram_fact(exitDx, cell_56, 0).
diagram_fact(exitDx, cell_61, 0).
diagram_fact(exitDx, cell_66, 0).
diagram_fact(exitDx, cell_71, 0).
diagram_fact(exitDx, cell_76, 0).
diagram_fact(exitDx, cell_81, 0).
diagram_fact(exitDx, cell_86, 0).
diagram_fact(exitDx, cell_91, 0).
diagram_fact(exitDx, cell_96, 0).
diagram_fact(exitDy, cell_10, 0).
diagram_fact(exitDy, cell_101, 0).
diagram_fact(exitDy, cell_106, 0).
diagram_fact(exitDy, cell_111, 0).
diagram_fact(exitDy, cell_15, 0).
diagram_fact(exitDy, cell_19, 0).
diagram_fact(exitDy, cell_24, 0).
diagram_fact(exitDy, cell_29, 0).
diagram_fact(exitDy, cell_34, 0).
diagram_fact(exitDy, cell_42, 0).
diagram_fact(exitDy, cell_44, 0).
diagram_fact(exitDy, cell_52, 0).
diagram_fact(exitDy, cell_56, 0).
diagram_fact(exitDy, cell_61, 0).
diagram_fact(exitDy, cell_66, 0).
diagram_fact(exitDy, cell_71, 0).
diagram_fact(exitDy, cell_76, 0).
diagram_fact(exitDy, cell_81, 0).
diagram_fact(exitDy, cell_86, 0).
diagram_fact(exitDy, cell_91, 0).
diagram_fact(exitDy, cell_96, 0).
diagram_fact(exitX, cell_10, 1).
diagram_fact(exitX, cell_101, 1).
diagram_fact(exitX, cell_106, 1).
diagram_fact(exitX, cell_111, 1).
diagram_fact(exitX, cell_15, 1).
diagram_fact(exitX, cell_19, 1).
diagram_fact(exitX, cell_24, 1).
diagram_fact(exitX, cell_29, 1).
diagram_fact(exitX, cell_34, 1).
diagram_fact(exitX, cell_42, 1).
diagram_fact(exitX, cell_44, 1).
diagram_fact(exitX, cell_52, 1).
diagram_fact(exitX, cell_56, 1).
diagram_fact(exitX, cell_61, 1).
diagram_fact(exitX, cell_66, 1).
diagram_fact(exitX, cell_71, 1).
diagram_fact(exitX, cell_76, 1).
diagram_fact(exitX, cell_81, 1).
diagram_fact(exitX, cell_86, 1).
diagram_fact(exitX, cell_91, 1).
diagram_fact(exitX, cell_96, 1).
diagram_fact(exitY, cell_10, 0.5).
diagram_fact(exitY, cell_101, 0.5).
diagram_fact(exitY, cell_106, 0.5).
diagram_fact(exitY, cell_111, 0.5).
diagram_fact(exitY, cell_15, 0.5).
diagram_fact(exitY, cell_19, 0.5).
diagram_fact(exitY, cell_24, 0.5).
diagram_fact(exitY, cell_29, 0.5).
diagram_fact(exitY, cell_34, 0.5).
diagram_fact(exitY, cell_42, 0.5).
diagram_fact(exitY, cell_44, 0.5).
diagram_fact(exitY, cell_52, 0.5).
diagram_fact(exitY, cell_56, 0.5).
diagram_fact(exitY, cell_61, 0.5).
diagram_fact(exitY, cell_66, 0.5).
diagram_fact(exitY, cell_71, 0.5).
diagram_fact(exitY, cell_76, 0.5).
diagram_fact(exitY, cell_81, 0.5).
diagram_fact(exitY, cell_86, 0.5).
diagram_fact(exitY, cell_91, 0.5).
diagram_fact(exitY, cell_96, 0.5).
diagram_fact(fillColor, cell_100, "#f8cecc").
diagram_fact(fillColor, cell_102, "#fff2cc").
diagram_fact(fillColor, cell_103, "#d5e8d4").
diagram_fact(fillColor, cell_104, "#dae8fc").
diagram_fact(fillColor, cell_105, "#f8cecc").
diagram_fact(fillColor, cell_107, "#fff2cc").
diagram_fact(fillColor, cell_108, "#d5e8d4").
diagram_fact(fillColor, cell_109, "#dae8fc").
diagram_fact(fillColor, cell_11, "#fff2cc").
diagram_fact(fillColor, cell_110, "#f8cecc").
diagram_fact(fillColor, cell_112, "#fff2cc").
diagram_fact(fillColor, cell_113, "#d5e8d4").
diagram_fact(fillColor, cell_12, "#d5e8d4").
diagram_fact(fillColor, cell_13, "#dae8fc").
diagram_fact(fillColor, cell_14, "#f8cecc").
diagram_fact(fillColor, cell_16, "#fff2cc").
diagram_fact(fillColor, cell_17, "#d5e8d4").
diagram_fact(fillColor, cell_18, "#f8cecc").
diagram_fact(fillColor, cell_20, "#fff2cc").
diagram_fact(fillColor, cell_21, "#d5e8d4").
diagram_fact(fillColor, cell_22, "#dae8fc").
diagram_fact(fillColor, cell_23, "#f8cecc").
diagram_fact(fillColor, cell_25, "#fff2cc").
diagram_fact(fillColor, cell_26, "#d5e8d4").
diagram_fact(fillColor, cell_27, "#dae8fc").
diagram_fact(fillColor, cell_28, "#f8cecc").
diagram_fact(fillColor, cell_30, "#fff2cc").
diagram_fact(fillColor, cell_31, "#d5e8d4").
diagram_fact(fillColor, cell_32, "#dae8fc").
diagram_fact(fillColor, cell_33, "#f8cecc").
diagram_fact(fillColor, cell_35, "#fff2cc").
diagram_fact(fillColor, cell_36, "#d5e8d4").
diagram_fact(fillColor, cell_37, "#dae8fc").
diagram_fact(fillColor, cell_38, "#f8cecc").
diagram_fact(fillColor, cell_39, "#d5e8d4").
diagram_fact(fillColor, cell_40, "#dae8fc").
diagram_fact(fillColor, cell_41, "#f8cecc").
diagram_fact(fillColor, cell_43, "#fff2cc").
diagram_fact(fillColor, cell_45, "#fff2cc").
diagram_fact(fillColor, cell_46, "#dae8fc").
diagram_fact(fillColor, cell_47, "#f8cecc").
diagram_fact(fillColor, cell_48, "#d5e8d4").
diagram_fact(fillColor, cell_49, "#dae8fc").
diagram_fact(fillColor, cell_50, "#f8cecc").
diagram_fact(fillColor, cell_51, "#d5e8d4").
diagram_fact(fillColor, cell_53, "#fff2cc").
diagram_fact(fillColor, cell_54, "#dae8fc").
diagram_fact(fillColor, cell_55, "#f8cecc").
diagram_fact(fillColor, cell_57, "#fff2cc").
diagram_fact(fillColor, cell_58, "#d5e8d4").
diagram_fact(fillColor, cell_59, "#dae8fc").
diagram_fact(fillColor, cell_60, "#f8cecc").
diagram_fact(fillColor, cell_62, "#fff2cc").
diagram_fact(fillColor, cell_63, "#d5e8d4").
diagram_fact(fillColor, cell_64, "#dae8fc").
diagram_fact(fillColor, cell_65, "#f8cecc").
diagram_fact(fillColor, cell_67, "#fff2cc").
diagram_fact(fillColor, cell_68, "#d5e8d4").
diagram_fact(fillColor, cell_69, "#dae8fc").
diagram_fact(fillColor, cell_7, "#dae8fc").
diagram_fact(fillColor, cell_70, "#f8cecc").
diagram_fact(fillColor, cell_72, "#fff2cc").
diagram_fact(fillColor, cell_73, "#d5e8d4").
diagram_fact(fillColor, cell_74, "#dae8fc").
diagram_fact(fillColor, cell_75, "#f8cecc").
diagram_fact(fillColor, cell_77, "#fff2cc").
diagram_fact(fillColor, cell_78, "#d5e8d4").
diagram_fact(fillColor, cell_79, "#dae8fc").
diagram_fact(fillColor, cell_8, "#dae8fc").
diagram_fact(fillColor, cell_80, "#f8cecc").
diagram_fact(fillColor, cell_82, "#fff2cc").
diagram_fact(fillColor, cell_83, "#d5e8d4").
diagram_fact(fillColor, cell_84, "#dae8fc").
diagram_fact(fillColor, cell_85, "#f8cecc").
diagram_fact(fillColor, cell_87, "#fff2cc").
diagram_fact(fillColor, cell_88, "#d5e8d4").
diagram_fact(fillColor, cell_89, "#dae8fc").
diagram_fact(fillColor, cell_9, "#f8cecc").
diagram_fact(fillColor, cell_90, "#f8cecc").
diagram_fact(fillColor, cell_92, "#fff2cc").
diagram_fact(fillColor, cell_93, "#d5e8d4").
diagram_fact(fillColor, cell_94, "#dae8fc").
diagram_fact(fillColor, cell_95, "#f8cecc").
diagram_fact(fillColor, cell_97, "#fff2cc").
diagram_fact(fillColor, cell_98, "#d5e8d4").
diagram_fact(fillColor, cell_99, "#dae8fc").
diagram_fact(gradientColor, cell_104, "#7ea6e0").
diagram_fact(gradientColor, cell_109, "#7ea6e0").
diagram_fact(gradientColor, cell_13, "#7ea6e0").
diagram_fact(gradientColor, cell_22, "#7ea6e0").
diagram_fact(gradientColor, cell_27, "#7ea6e0").
diagram_fact(gradientColor, cell_32, "#7ea6e0").
diagram_fact(gradientColor, cell_37, "#7ea6e0").
diagram_fact(gradientColor, cell_40, "#7ea6e0").
diagram_fact(gradientColor, cell_46, "#7ea6e0").
diagram_fact(gradientColor, cell_49, "#7ea6e0").
diagram_fact(gradientColor, cell_54, "#7ea6e0").
diagram_fact(gradientColor, cell_59, "#7ea6e0").
diagram_fact(gradientColor, cell_64, "#7ea6e0").
diagram_fact(gradientColor, cell_69, "#7ea6e0").
diagram_fact(gradientColor, cell_7, "#7ea6e0").
diagram_fact(gradientColor, cell_74, "#7ea6e0").
diagram_fact(gradientColor, cell_79, "#7ea6e0").
diagram_fact(gradientColor, cell_8, "#7ea6e0").
diagram_fact(gradientColor, cell_84, "#7ea6e0").
diagram_fact(gradientColor, cell_89, "#7ea6e0").
diagram_fact(gradientColor, cell_94, "#7ea6e0").
diagram_fact(gradientColor, cell_99, "#7ea6e0").
diagram_fact(height, cell_100, 45).
diagram_fact(height, cell_102, 40).
diagram_fact(height, cell_103, 40).
diagram_fact(height, cell_104, 130).
diagram_fact(height, cell_105, 45).
diagram_fact(height, cell_107, 40).
diagram_fact(height, cell_108, 40).
diagram_fact(height, cell_109, 130).
diagram_fact(height, cell_11, 40).
diagram_fact(height, cell_110, 45).
diagram_fact(height, cell_112, 40).
diagram_fact(height, cell_113, 40).
diagram_fact(height, cell_12, 40).
diagram_fact(height, cell_13, 130).
diagram_fact(height, cell_14, 45).
diagram_fact(height, cell_16, 40).
diagram_fact(height, cell_17, 40).
diagram_fact(height, cell_18, 45).
diagram_fact(height, cell_20, 40).
diagram_fact(height, cell_21, 40).
diagram_fact(height, cell_22, 130).
diagram_fact(height, cell_23, 45).
diagram_fact(height, cell_25, 40).
diagram_fact(height, cell_26, 40).
diagram_fact(height, cell_27, 130).
diagram_fact(height, cell_28, 45).
diagram_fact(height, cell_30, 40).
diagram_fact(height, cell_31, 40).
diagram_fact(height, cell_32, 130).
diagram_fact(height, cell_33, 45).
diagram_fact(height, cell_35, 40).
diagram_fact(height, cell_36, 40).
diagram_fact(height, cell_37, 130).
diagram_fact(height, cell_38, 45).
diagram_fact(height, cell_39, 40).
diagram_fact(height, cell_40, 130).
diagram_fact(height, cell_41, 45).
diagram_fact(height, cell_43, 40).
diagram_fact(height, cell_45, 40).
diagram_fact(height, cell_46, 130).
diagram_fact(height, cell_47, 65).
diagram_fact(height, cell_48, 40).
diagram_fact(height, cell_49, 130).
diagram_fact(height, cell_50, 45).
diagram_fact(height, cell_51, 40).
diagram_fact(height, cell_53, 40).
diagram_fact(height, cell_54, 130).
diagram_fact(height, cell_55, 45).
diagram_fact(height, cell_57, 40).
diagram_fact(height, cell_58, 40).
diagram_fact(height, cell_59, 130).
diagram_fact(height, cell_6, 3500).
diagram_fact(height, cell_60, 45).
diagram_fact(height, cell_62, 40).
diagram_fact(height, cell_63, 40).
diagram_fact(height, cell_64, 130).
diagram_fact(height, cell_65, 45).
diagram_fact(height, cell_67, 40).
diagram_fact(height, cell_68, 40).
diagram_fact(height, cell_69, 130).
diagram_fact(height, cell_7, 130).
diagram_fact(height, cell_70, 45).
diagram_fact(height, cell_72, 40).
diagram_fact(height, cell_73, 40).
diagram_fact(height, cell_74, 130).
diagram_fact(height, cell_75, 45).
diagram_fact(height, cell_77, 40).
diagram_fact(height, cell_78, 40).
diagram_fact(height, cell_79, 130).
diagram_fact(height, cell_8, 130).
diagram_fact(height, cell_80, 45).
diagram_fact(height, cell_82, 40).
diagram_fact(height, cell_83, 40).
diagram_fact(height, cell_84, 130).
diagram_fact(height, cell_85, 45).
diagram_fact(height, cell_87, 40).
diagram_fact(height, cell_88, 40).
diagram_fact(height, cell_89, 130).
diagram_fact(height, cell_9, 45).
diagram_fact(height, cell_90, 45).
diagram_fact(height, cell_92, 40).
diagram_fact(height, cell_93, 40).
diagram_fact(height, cell_94, 130).
diagram_fact(height, cell_95, 45).
diagram_fact(height, cell_97, 40).
diagram_fact(height, cell_98, 40).
diagram_fact(height, cell_99, 130).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_100, 1).
diagram_fact(html, cell_101, 1).
diagram_fact(html, cell_102, 1).
diagram_fact(html, cell_103, 1).
diagram_fact(html, cell_104, 1).
diagram_fact(html, cell_105, 1).
diagram_fact(html, cell_106, 1).
diagram_fact(html, cell_107, 1).
diagram_fact(html, cell_108, 1).
diagram_fact(html, cell_109, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_110, 1).
diagram_fact(html, cell_111, 1).
diagram_fact(html, cell_112, 1).
diagram_fact(html, cell_113, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_17, 1).
diagram_fact(html, cell_18, 1).
diagram_fact(html, cell_19, 1).
diagram_fact(html, cell_20, 1).
diagram_fact(html, cell_21, 1).
diagram_fact(html, cell_22, 1).
diagram_fact(html, cell_23, 1).
diagram_fact(html, cell_24, 1).
diagram_fact(html, cell_25, 1).
diagram_fact(html, cell_26, 1).
diagram_fact(html, cell_27, 1).
diagram_fact(html, cell_28, 1).
diagram_fact(html, cell_29, 1).
diagram_fact(html, cell_30, 1).
diagram_fact(html, cell_31, 1).
diagram_fact(html, cell_32, 1).
diagram_fact(html, cell_33, 1).
diagram_fact(html, cell_34, 1).
diagram_fact(html, cell_35, 1).
diagram_fact(html, cell_36, 1).
diagram_fact(html, cell_37, 1).
diagram_fact(html, cell_38, 1).
diagram_fact(html, cell_39, 1).
diagram_fact(html, cell_40, 1).
diagram_fact(html, cell_41, 1).
diagram_fact(html, cell_42, 1).
diagram_fact(html, cell_43, 1).
diagram_fact(html, cell_44, 1).
diagram_fact(html, cell_45, 1).
diagram_fact(html, cell_46, 1).
diagram_fact(html, cell_47, 1).
diagram_fact(html, cell_48, 1).
diagram_fact(html, cell_49, 1).
diagram_fact(html, cell_50, 1).
diagram_fact(html, cell_51, 1).
diagram_fact(html, cell_52, 1).
diagram_fact(html, cell_53, 1).
diagram_fact(html, cell_54, 1).
diagram_fact(html, cell_55, 1).
diagram_fact(html, cell_56, 1).
diagram_fact(html, cell_57, 1).
diagram_fact(html, cell_58, 1).
diagram_fact(html, cell_59, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_60, 1).
diagram_fact(html, cell_61, 1).
diagram_fact(html, cell_62, 1).
diagram_fact(html, cell_63, 1).
diagram_fact(html, cell_64, 1).
diagram_fact(html, cell_65, 1).
diagram_fact(html, cell_66, 1).
diagram_fact(html, cell_67, 1).
diagram_fact(html, cell_68, 1).
diagram_fact(html, cell_69, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_70, 1).
diagram_fact(html, cell_71, 1).
diagram_fact(html, cell_72, 1).
diagram_fact(html, cell_73, 1).
diagram_fact(html, cell_74, 1).
diagram_fact(html, cell_75, 1).
diagram_fact(html, cell_76, 1).
diagram_fact(html, cell_77, 1).
diagram_fact(html, cell_78, 1).
diagram_fact(html, cell_79, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_80, 1).
diagram_fact(html, cell_81, 1).
diagram_fact(html, cell_82, 1).
diagram_fact(html, cell_83, 1).
diagram_fact(html, cell_84, 1).
diagram_fact(html, cell_85, 1).
diagram_fact(html, cell_86, 1).
diagram_fact(html, cell_87, 1).
diagram_fact(html, cell_88, 1).
diagram_fact(html, cell_89, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(html, cell_90, 1).
diagram_fact(html, cell_91, 1).
diagram_fact(html, cell_92, 1).
diagram_fact(html, cell_93, 1).
diagram_fact(html, cell_94, 1).
diagram_fact(html, cell_95, 1).
diagram_fact(html, cell_96, 1).
diagram_fact(html, cell_97, 1).
diagram_fact(html, cell_98, 1).
diagram_fact(html, cell_99, 1).
diagram_fact(jettySize, cell_10, "auto").
diagram_fact(jettySize, cell_101, "auto").
diagram_fact(jettySize, cell_106, "auto").
diagram_fact(jettySize, cell_111, "auto").
diagram_fact(jettySize, cell_15, "auto").
diagram_fact(jettySize, cell_19, "auto").
diagram_fact(jettySize, cell_24, "auto").
diagram_fact(jettySize, cell_29, "auto").
diagram_fact(jettySize, cell_34, "auto").
diagram_fact(jettySize, cell_42, "auto").
diagram_fact(jettySize, cell_44, "auto").
diagram_fact(jettySize, cell_52, "auto").
diagram_fact(jettySize, cell_56, "auto").
diagram_fact(jettySize, cell_61, "auto").
diagram_fact(jettySize, cell_66, "auto").
diagram_fact(jettySize, cell_71, "auto").
diagram_fact(jettySize, cell_76, "auto").
diagram_fact(jettySize, cell_81, "auto").
diagram_fact(jettySize, cell_86, "auto").
diagram_fact(jettySize, cell_91, "auto").
diagram_fact(jettySize, cell_96, "auto").
diagram_fact(kind, cell_102, "ellipse").
diagram_fact(kind, cell_103, "ellipse").
diagram_fact(kind, cell_107, "ellipse").
diagram_fact(kind, cell_108, "ellipse").
diagram_fact(kind, cell_11, "ellipse").
diagram_fact(kind, cell_112, "ellipse").
diagram_fact(kind, cell_113, "ellipse").
diagram_fact(kind, cell_12, "ellipse").
diagram_fact(kind, cell_16, "ellipse").
diagram_fact(kind, cell_17, "ellipse").
diagram_fact(kind, cell_20, "ellipse").
diagram_fact(kind, cell_21, "ellipse").
diagram_fact(kind, cell_25, "ellipse").
diagram_fact(kind, cell_26, "ellipse").
diagram_fact(kind, cell_30, "ellipse").
diagram_fact(kind, cell_31, "ellipse").
diagram_fact(kind, cell_35, "ellipse").
diagram_fact(kind, cell_36, "ellipse").
diagram_fact(kind, cell_39, "ellipse").
diagram_fact(kind, cell_43, "ellipse").
diagram_fact(kind, cell_45, "ellipse").
diagram_fact(kind, cell_48, "ellipse").
diagram_fact(kind, cell_51, "ellipse").
diagram_fact(kind, cell_53, "ellipse").
diagram_fact(kind, cell_57, "ellipse").
diagram_fact(kind, cell_58, "ellipse").
diagram_fact(kind, cell_62, "ellipse").
diagram_fact(kind, cell_63, "ellipse").
diagram_fact(kind, cell_67, "ellipse").
diagram_fact(kind, cell_68, "ellipse").
diagram_fact(kind, cell_72, "ellipse").
diagram_fact(kind, cell_73, "ellipse").
diagram_fact(kind, cell_77, "ellipse").
diagram_fact(kind, cell_78, "ellipse").
diagram_fact(kind, cell_82, "ellipse").
diagram_fact(kind, cell_83, "ellipse").
diagram_fact(kind, cell_87, "ellipse").
diagram_fact(kind, cell_88, "ellipse").
diagram_fact(kind, cell_92, "ellipse").
diagram_fact(kind, cell_93, "ellipse").
diagram_fact(kind, cell_97, "ellipse").
diagram_fact(kind, cell_98, "ellipse").
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(name, diagram_1, "d2f").
diagram_fact(orthogonalLoop, cell_10, 1).
diagram_fact(orthogonalLoop, cell_101, 1).
diagram_fact(orthogonalLoop, cell_106, 1).
diagram_fact(orthogonalLoop, cell_111, 1).
diagram_fact(orthogonalLoop, cell_15, 1).
diagram_fact(orthogonalLoop, cell_19, 1).
diagram_fact(orthogonalLoop, cell_24, 1).
diagram_fact(orthogonalLoop, cell_29, 1).
diagram_fact(orthogonalLoop, cell_34, 1).
diagram_fact(orthogonalLoop, cell_42, 1).
diagram_fact(orthogonalLoop, cell_44, 1).
diagram_fact(orthogonalLoop, cell_52, 1).
diagram_fact(orthogonalLoop, cell_56, 1).
diagram_fact(orthogonalLoop, cell_61, 1).
diagram_fact(orthogonalLoop, cell_66, 1).
diagram_fact(orthogonalLoop, cell_71, 1).
diagram_fact(orthogonalLoop, cell_76, 1).
diagram_fact(orthogonalLoop, cell_81, 1).
diagram_fact(orthogonalLoop, cell_86, 1).
diagram_fact(orthogonalLoop, cell_91, 1).
diagram_fact(orthogonalLoop, cell_96, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_100, id_1).
diagram_fact(parent, cell_101, id_1).
diagram_fact(parent, cell_102, id_1).
diagram_fact(parent, cell_103, id_1).
diagram_fact(parent, cell_104, id_1).
diagram_fact(parent, cell_105, id_1).
diagram_fact(parent, cell_106, id_1).
diagram_fact(parent, cell_107, id_1).
diagram_fact(parent, cell_108, id_1).
diagram_fact(parent, cell_109, id_1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_110, id_1).
diagram_fact(parent, cell_111, id_1).
diagram_fact(parent, cell_112, id_1).
diagram_fact(parent, cell_113, id_1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_17, id_1).
diagram_fact(parent, cell_18, id_1).
diagram_fact(parent, cell_19, id_1).
diagram_fact(parent, cell_20, id_1).
diagram_fact(parent, cell_21, id_1).
diagram_fact(parent, cell_22, id_1).
diagram_fact(parent, cell_23, id_1).
diagram_fact(parent, cell_24, id_1).
diagram_fact(parent, cell_25, id_1).
diagram_fact(parent, cell_26, id_1).
diagram_fact(parent, cell_27, id_1).
diagram_fact(parent, cell_28, id_1).
diagram_fact(parent, cell_29, id_1).
diagram_fact(parent, cell_30, id_1).
diagram_fact(parent, cell_31, id_1).
diagram_fact(parent, cell_32, id_1).
diagram_fact(parent, cell_33, id_1).
diagram_fact(parent, cell_34, id_1).
diagram_fact(parent, cell_35, id_1).
diagram_fact(parent, cell_36, id_1).
diagram_fact(parent, cell_37, id_1).
diagram_fact(parent, cell_38, id_1).
diagram_fact(parent, cell_39, id_1).
diagram_fact(parent, cell_40, id_1).
diagram_fact(parent, cell_41, id_1).
diagram_fact(parent, cell_42, id_1).
diagram_fact(parent, cell_43, id_1).
diagram_fact(parent, cell_44, id_1).
diagram_fact(parent, cell_45, id_1).
diagram_fact(parent, cell_46, id_1).
diagram_fact(parent, cell_47, id_1).
diagram_fact(parent, cell_48, id_1).
diagram_fact(parent, cell_49, id_1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_50, id_1).
diagram_fact(parent, cell_51, id_1).
diagram_fact(parent, cell_52, id_1).
diagram_fact(parent, cell_53, id_1).
diagram_fact(parent, cell_54, id_1).
diagram_fact(parent, cell_55, id_1).
diagram_fact(parent, cell_56, id_1).
diagram_fact(parent, cell_57, id_1).
diagram_fact(parent, cell_58, id_1).
diagram_fact(parent, cell_59, id_1).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_60, id_1).
diagram_fact(parent, cell_61, id_1).
diagram_fact(parent, cell_62, id_1).
diagram_fact(parent, cell_63, id_1).
diagram_fact(parent, cell_64, id_1).
diagram_fact(parent, cell_65, id_1).
diagram_fact(parent, cell_66, id_1).
diagram_fact(parent, cell_67, id_1).
diagram_fact(parent, cell_68, id_1).
diagram_fact(parent, cell_69, id_1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_70, id_1).
diagram_fact(parent, cell_71, id_1).
diagram_fact(parent, cell_72, id_1).
diagram_fact(parent, cell_73, id_1).
diagram_fact(parent, cell_74, id_1).
diagram_fact(parent, cell_75, id_1).
diagram_fact(parent, cell_76, id_1).
diagram_fact(parent, cell_77, id_1).
diagram_fact(parent, cell_78, id_1).
diagram_fact(parent, cell_79, id_1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_80, id_1).
diagram_fact(parent, cell_81, id_1).
diagram_fact(parent, cell_82, id_1).
diagram_fact(parent, cell_83, id_1).
diagram_fact(parent, cell_84, id_1).
diagram_fact(parent, cell_85, id_1).
diagram_fact(parent, cell_86, id_1).
diagram_fact(parent, cell_87, id_1).
diagram_fact(parent, cell_88, id_1).
diagram_fact(parent, cell_89, id_1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(parent, cell_90, id_1).
diagram_fact(parent, cell_91, id_1).
diagram_fact(parent, cell_92, id_1).
diagram_fact(parent, cell_93, id_1).
diagram_fact(parent, cell_94, id_1).
diagram_fact(parent, cell_95, id_1).
diagram_fact(parent, cell_96, id_1).
diagram_fact(parent, cell_97, id_1).
diagram_fact(parent, cell_98, id_1).
diagram_fact(parent, cell_99, id_1).
diagram_fact(relative, cell_10, 1).
diagram_fact(relative, cell_101, 1).
diagram_fact(relative, cell_106, 1).
diagram_fact(relative, cell_111, 1).
diagram_fact(relative, cell_15, 1).
diagram_fact(relative, cell_19, 1).
diagram_fact(relative, cell_24, 1).
diagram_fact(relative, cell_29, 1).
diagram_fact(relative, cell_34, 1).
diagram_fact(relative, cell_42, 1).
diagram_fact(relative, cell_44, 1).
diagram_fact(relative, cell_52, 1).
diagram_fact(relative, cell_56, 1).
diagram_fact(relative, cell_61, 1).
diagram_fact(relative, cell_66, 1).
diagram_fact(relative, cell_71, 1).
diagram_fact(relative, cell_76, 1).
diagram_fact(relative, cell_81, 1).
diagram_fact(relative, cell_86, 1).
diagram_fact(relative, cell_91, 1).
diagram_fact(relative, cell_96, 1).
diagram_fact(root, root_3, root_3).
diagram_fact(rounded, cell_10, 0).
diagram_fact(rounded, cell_100, 0).
diagram_fact(rounded, cell_101, 0).
diagram_fact(rounded, cell_104, 1).
diagram_fact(rounded, cell_105, 0).
diagram_fact(rounded, cell_106, 0).
diagram_fact(rounded, cell_109, 1).
diagram_fact(rounded, cell_110, 0).
diagram_fact(rounded, cell_111, 0).
diagram_fact(rounded, cell_13, 1).
diagram_fact(rounded, cell_14, 0).
diagram_fact(rounded, cell_15, 0).
diagram_fact(rounded, cell_18, 0).
diagram_fact(rounded, cell_19, 0).
diagram_fact(rounded, cell_22, 1).
diagram_fact(rounded, cell_23, 0).
diagram_fact(rounded, cell_24, 0).
diagram_fact(rounded, cell_27, 1).
diagram_fact(rounded, cell_28, 0).
diagram_fact(rounded, cell_29, 0).
diagram_fact(rounded, cell_32, 1).
diagram_fact(rounded, cell_33, 0).
diagram_fact(rounded, cell_34, 0).
diagram_fact(rounded, cell_37, 1).
diagram_fact(rounded, cell_38, 0).
diagram_fact(rounded, cell_40, 1).
diagram_fact(rounded, cell_41, 0).
diagram_fact(rounded, cell_42, 0).
diagram_fact(rounded, cell_44, 0).
diagram_fact(rounded, cell_46, 1).
diagram_fact(rounded, cell_47, 0).
diagram_fact(rounded, cell_49, 1).
diagram_fact(rounded, cell_50, 0).
diagram_fact(rounded, cell_52, 0).
diagram_fact(rounded, cell_54, 1).
diagram_fact(rounded, cell_55, 0).
diagram_fact(rounded, cell_56, 0).
diagram_fact(rounded, cell_59, 1).
diagram_fact(rounded, cell_6, 1).
diagram_fact(rounded, cell_60, 0).
diagram_fact(rounded, cell_61, 0).
diagram_fact(rounded, cell_64, 1).
diagram_fact(rounded, cell_65, 0).
diagram_fact(rounded, cell_66, 0).
diagram_fact(rounded, cell_69, 1).
diagram_fact(rounded, cell_7, 1).
diagram_fact(rounded, cell_70, 0).
diagram_fact(rounded, cell_71, 0).
diagram_fact(rounded, cell_74, 1).
diagram_fact(rounded, cell_75, 0).
diagram_fact(rounded, cell_76, 0).
diagram_fact(rounded, cell_79, 1).
diagram_fact(rounded, cell_8, 1).
diagram_fact(rounded, cell_80, 0).
diagram_fact(rounded, cell_81, 0).
diagram_fact(rounded, cell_84, 1).
diagram_fact(rounded, cell_85, 0).
diagram_fact(rounded, cell_86, 0).
diagram_fact(rounded, cell_89, 1).
diagram_fact(rounded, cell_9, 0).
diagram_fact(rounded, cell_90, 0).
diagram_fact(rounded, cell_91, 0).
diagram_fact(rounded, cell_94, 1).
diagram_fact(rounded, cell_95, 0).
diagram_fact(rounded, cell_96, 0).
diagram_fact(rounded, cell_99, 1).
diagram_fact(source, cell_10, i5jZ3dy8F4nkPbaXPHF6__5).
diagram_fact(source, cell_101, id_N7UU1hHrbHNw5_2dAuh____45).
diagram_fact(source, cell_106, id_N7UU1hHrbHNw5_2dAuh____49).
diagram_fact(source, cell_111, id_N7UU1hHrbHNw5_2dAuh____53).
diagram_fact(source, cell_15, aPelzSQw_j5YxlEaLFGD__38).
diagram_fact(source, cell_19, aPelzSQw_j5YxlEaLFGD__45).
diagram_fact(source, cell_24, aPelzSQw_j5YxlEaLFGD__49).
diagram_fact(source, cell_29, aPelzSQw_j5YxlEaLFGD__54).
diagram_fact(source, cell_34, aPelzSQw_j5YxlEaLFGD__70).
diagram_fact(source, cell_42, id_MeUOVAnX9PiKFy5EPber__4).
diagram_fact(source, cell_44, id_9_2W__ZNaL5BkT9HVN__QL__3).
diagram_fact(source, cell_52, id_IZh1Ggwe__xGZHwZ9__CIt__5).
diagram_fact(source, cell_56, id_N7UU1hHrbHNw5_2dAuh____3).
diagram_fact(source, cell_61, id_N7UU1hHrbHNw5_2dAuh____7).
diagram_fact(source, cell_66, id_N7UU1hHrbHNw5_2dAuh____11).
diagram_fact(source, cell_71, id_N7UU1hHrbHNw5_2dAuh____15).
diagram_fact(source, cell_76, id_N7UU1hHrbHNw5_2dAuh____20).
diagram_fact(source, cell_81, id_N7UU1hHrbHNw5_2dAuh____25).
diagram_fact(source, cell_86, id_N7UU1hHrbHNw5_2dAuh____29).
diagram_fact(source, cell_91, id_N7UU1hHrbHNw5_2dAuh____33).
diagram_fact(source, cell_96, id_N7UU1hHrbHNw5_2dAuh____40).
diagram_fact(strokeColor, cell_100, "#b85450").
diagram_fact(strokeColor, cell_102, "#d6b656").
diagram_fact(strokeColor, cell_103, "#82b366").
diagram_fact(strokeColor, cell_104, "#6c8ebf").
diagram_fact(strokeColor, cell_105, "#b85450").
diagram_fact(strokeColor, cell_107, "#d6b656").
diagram_fact(strokeColor, cell_108, "#82b366").
diagram_fact(strokeColor, cell_109, "#6c8ebf").
diagram_fact(strokeColor, cell_11, "#d6b656").
diagram_fact(strokeColor, cell_110, "#b85450").
diagram_fact(strokeColor, cell_112, "#d6b656").
diagram_fact(strokeColor, cell_113, "#82b366").
diagram_fact(strokeColor, cell_12, "#82b366").
diagram_fact(strokeColor, cell_13, "#6c8ebf").
diagram_fact(strokeColor, cell_14, "#b85450").
diagram_fact(strokeColor, cell_16, "#d6b656").
diagram_fact(strokeColor, cell_17, "#82b366").
diagram_fact(strokeColor, cell_18, "#b85450").
diagram_fact(strokeColor, cell_20, "#d6b656").
diagram_fact(strokeColor, cell_21, "#82b366").
diagram_fact(strokeColor, cell_22, "#6c8ebf").
diagram_fact(strokeColor, cell_23, "#b85450").
diagram_fact(strokeColor, cell_25, "#d6b656").
diagram_fact(strokeColor, cell_26, "#82b366").
diagram_fact(strokeColor, cell_27, "#6c8ebf").
diagram_fact(strokeColor, cell_28, "#b85450").
diagram_fact(strokeColor, cell_30, "#d6b656").
diagram_fact(strokeColor, cell_31, "#82b366").
diagram_fact(strokeColor, cell_32, "#6c8ebf").
diagram_fact(strokeColor, cell_33, "#b85450").
diagram_fact(strokeColor, cell_35, "#d6b656").
diagram_fact(strokeColor, cell_36, "#82b366").
diagram_fact(strokeColor, cell_37, "#6c8ebf").
diagram_fact(strokeColor, cell_38, "#b85450").
diagram_fact(strokeColor, cell_39, "#82b366").
diagram_fact(strokeColor, cell_40, "#6c8ebf").
diagram_fact(strokeColor, cell_41, "#b85450").
diagram_fact(strokeColor, cell_43, "#d6b656").
diagram_fact(strokeColor, cell_45, "#d6b656").
diagram_fact(strokeColor, cell_46, "#6c8ebf").
diagram_fact(strokeColor, cell_47, "#b85450").
diagram_fact(strokeColor, cell_48, "#82b366").
diagram_fact(strokeColor, cell_49, "#6c8ebf").
diagram_fact(strokeColor, cell_50, "#b85450").
diagram_fact(strokeColor, cell_51, "#82b366").
diagram_fact(strokeColor, cell_53, "#d6b656").
diagram_fact(strokeColor, cell_54, "#6c8ebf").
diagram_fact(strokeColor, cell_55, "#b85450").
diagram_fact(strokeColor, cell_57, "#d6b656").
diagram_fact(strokeColor, cell_58, "#82b366").
diagram_fact(strokeColor, cell_59, "#6c8ebf").
diagram_fact(strokeColor, cell_60, "#b85450").
diagram_fact(strokeColor, cell_62, "#d6b656").
diagram_fact(strokeColor, cell_63, "#82b366").
diagram_fact(strokeColor, cell_64, "#6c8ebf").
diagram_fact(strokeColor, cell_65, "#b85450").
diagram_fact(strokeColor, cell_67, "#d6b656").
diagram_fact(strokeColor, cell_68, "#82b366").
diagram_fact(strokeColor, cell_69, "#6c8ebf").
diagram_fact(strokeColor, cell_7, "#6c8ebf").
diagram_fact(strokeColor, cell_70, "#b85450").
diagram_fact(strokeColor, cell_72, "#d6b656").
diagram_fact(strokeColor, cell_73, "#82b366").
diagram_fact(strokeColor, cell_74, "#6c8ebf").
diagram_fact(strokeColor, cell_75, "#b85450").
diagram_fact(strokeColor, cell_77, "#d6b656").
diagram_fact(strokeColor, cell_78, "#82b366").
diagram_fact(strokeColor, cell_79, "#6c8ebf").
diagram_fact(strokeColor, cell_8, "#6c8ebf").
diagram_fact(strokeColor, cell_80, "#b85450").
diagram_fact(strokeColor, cell_82, "#d6b656").
diagram_fact(strokeColor, cell_83, "#82b366").
diagram_fact(strokeColor, cell_84, "#6c8ebf").
diagram_fact(strokeColor, cell_85, "#b85450").
diagram_fact(strokeColor, cell_87, "#d6b656").
diagram_fact(strokeColor, cell_88, "#82b366").
diagram_fact(strokeColor, cell_89, "#6c8ebf").
diagram_fact(strokeColor, cell_9, "#b85450").
diagram_fact(strokeColor, cell_90, "#b85450").
diagram_fact(strokeColor, cell_92, "#d6b656").
diagram_fact(strokeColor, cell_93, "#82b366").
diagram_fact(strokeColor, cell_94, "#6c8ebf").
diagram_fact(strokeColor, cell_95, "#b85450").
diagram_fact(strokeColor, cell_97, "#d6b656").
diagram_fact(strokeColor, cell_98, "#82b366").
diagram_fact(strokeColor, cell_99, "#6c8ebf").
diagram_fact(synonym, cell_10, aPelzSQw_j5YxlEaLFGD__40).
diagram_fact(synonym, cell_100, id_N7UU1hHrbHNw5_2dAuh____43).
diagram_fact(synonym, cell_101, id_N7UU1hHrbHNw5_2dAuh____44).
diagram_fact(synonym, cell_102, id_N7UU1hHrbHNw5_2dAuh____45).
diagram_fact(synonym, cell_103, id_N7UU1hHrbHNw5_2dAuh____46).
diagram_fact(synonym, cell_104, id_N7UU1hHrbHNw5_2dAuh____47).
diagram_fact(synonym, cell_105, id_N7UU1hHrbHNw5_2dAuh____48).
diagram_fact(synonym, cell_106, id_N7UU1hHrbHNw5_2dAuh____55).
diagram_fact(synonym, cell_107, id_N7UU1hHrbHNw5_2dAuh____49).
diagram_fact(synonym, cell_108, id_N7UU1hHrbHNw5_2dAuh____50).
diagram_fact(synonym, cell_109, id_N7UU1hHrbHNw5_2dAuh____51).
diagram_fact(synonym, cell_11, i5jZ3dy8F4nkPbaXPHF6__5).
diagram_fact(synonym, cell_110, id_N7UU1hHrbHNw5_2dAuh____52).
diagram_fact(synonym, cell_111, id_N7UU1hHrbHNw5_2dAuh____64).
diagram_fact(synonym, cell_112, id_N7UU1hHrbHNw5_2dAuh____53).
diagram_fact(synonym, cell_113, id_N7UU1hHrbHNw5_2dAuh____54).
diagram_fact(synonym, cell_12, id_Eg2JflB1LH7_nM4HlBUV__2).
diagram_fact(synonym, cell_13, aPelzSQw_j5YxlEaLFGD__36).
diagram_fact(synonym, cell_14, aPelzSQw_j5YxlEaLFGD__37).
diagram_fact(synonym, cell_15, aPelzSQw_j5YxlEaLFGD__60).
diagram_fact(synonym, cell_16, aPelzSQw_j5YxlEaLFGD__38).
diagram_fact(synonym, cell_17, aPelzSQw_j5YxlEaLFGD__39).
diagram_fact(synonym, cell_18, aPelzSQw_j5YxlEaLFGD__43).
diagram_fact(synonym, cell_19, aPelzSQw_j5YxlEaLFGD__44).
diagram_fact(synonym, cell_20, aPelzSQw_j5YxlEaLFGD__45).
diagram_fact(synonym, cell_21, aPelzSQw_j5YxlEaLFGD__46).
diagram_fact(synonym, cell_22, aPelzSQw_j5YxlEaLFGD__47).
diagram_fact(synonym, cell_23, aPelzSQw_j5YxlEaLFGD__48).
diagram_fact(synonym, cell_24, aPelzSQw_j5YxlEaLFGD__61).
diagram_fact(synonym, cell_25, aPelzSQw_j5YxlEaLFGD__49).
diagram_fact(synonym, cell_26, aPelzSQw_j5YxlEaLFGD__50).
diagram_fact(synonym, cell_27, aPelzSQw_j5YxlEaLFGD__51).
diagram_fact(synonym, cell_28, aPelzSQw_j5YxlEaLFGD__52).
diagram_fact(synonym, cell_29, aPelzSQw_j5YxlEaLFGD__72).
diagram_fact(synonym, cell_30, aPelzSQw_j5YxlEaLFGD__54).
diagram_fact(synonym, cell_31, aPelzSQw_j5YxlEaLFGD__55).
diagram_fact(synonym, cell_32, aPelzSQw_j5YxlEaLFGD__68).
diagram_fact(synonym, cell_33, aPelzSQw_j5YxlEaLFGD__69).
diagram_fact(synonym, cell_34, aPelzSQw_j5YxlEaLFGD__77).
diagram_fact(synonym, cell_35, aPelzSQw_j5YxlEaLFGD__70).
diagram_fact(synonym, cell_36, aPelzSQw_j5YxlEaLFGD__71).
diagram_fact(synonym, cell_37, aPelzSQw_j5YxlEaLFGD__73).
diagram_fact(synonym, cell_38, aPelzSQw_j5YxlEaLFGD__74).
diagram_fact(synonym, cell_39, aPelzSQw_j5YxlEaLFGD__76).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_40, id_MeUOVAnX9PiKFy5EPber__2).
diagram_fact(synonym, cell_41, id_MeUOVAnX9PiKFy5EPber__3).
diagram_fact(synonym, cell_42, id_MeUOVAnX9PiKFy5EPber__7).
diagram_fact(synonym, cell_43, id_MeUOVAnX9PiKFy5EPber__4).
diagram_fact(synonym, cell_44, id_N7UU1hHrbHNw5_2dAuh____62).
diagram_fact(synonym, cell_45, id_9_2W__ZNaL5BkT9HVN__QL__3).
diagram_fact(synonym, cell_46, id_9_2W__ZNaL5BkT9HVN__QL__6).
diagram_fact(synonym, cell_47, id_9_2W__ZNaL5BkT9HVN__QL__7).
diagram_fact(synonym, cell_48, id_9_2W__ZNaL5BkT9HVN__QL__8).
diagram_fact(synonym, cell_49, id_IZh1Ggwe__xGZHwZ9__CIt__2).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_50, id_IZh1Ggwe__xGZHwZ9__CIt__3).
diagram_fact(synonym, cell_51, id_IZh1Ggwe__xGZHwZ9__CIt__4).
diagram_fact(synonym, cell_52, id_N7UU1hHrbHNw5_2dAuh____65).
diagram_fact(synonym, cell_53, id_IZh1Ggwe__xGZHwZ9__CIt__5).
diagram_fact(synonym, cell_54, id_N7UU1hHrbHNw5_2dAuh____1).
diagram_fact(synonym, cell_55, id_N7UU1hHrbHNw5_2dAuh____2).
diagram_fact(synonym, cell_56, id_N7UU1hHrbHNw5_2dAuh____60).
diagram_fact(synonym, cell_57, id_N7UU1hHrbHNw5_2dAuh____3).
diagram_fact(synonym, cell_58, id_N7UU1hHrbHNw5_2dAuh____4).
diagram_fact(synonym, cell_59, id_N7UU1hHrbHNw5_2dAuh____5).
diagram_fact(synonym, cell_6, i5jZ3dy8F4nkPbaXPHF6__1).
diagram_fact(synonym, cell_60, id_N7UU1hHrbHNw5_2dAuh____6).
diagram_fact(synonym, cell_61, id_N7UU1hHrbHNw5_2dAuh____17).
diagram_fact(synonym, cell_62, id_N7UU1hHrbHNw5_2dAuh____7).
diagram_fact(synonym, cell_63, id_N7UU1hHrbHNw5_2dAuh____8).
diagram_fact(synonym, cell_64, id_N7UU1hHrbHNw5_2dAuh____9).
diagram_fact(synonym, cell_65, id_N7UU1hHrbHNw5_2dAuh____10).
diagram_fact(synonym, cell_66, id_N7UU1hHrbHNw5_2dAuh____59).
diagram_fact(synonym, cell_67, id_N7UU1hHrbHNw5_2dAuh____11).
diagram_fact(synonym, cell_68, id_N7UU1hHrbHNw5_2dAuh____12).
diagram_fact(synonym, cell_69, id_N7UU1hHrbHNw5_2dAuh____13).
diagram_fact(synonym, cell_7, aPelzSQw_j5YxlEaLFGD__42).
diagram_fact(synonym, cell_70, id_N7UU1hHrbHNw5_2dAuh____14).
diagram_fact(synonym, cell_71, id_N7UU1hHrbHNw5_2dAuh____37).
diagram_fact(synonym, cell_72, id_N7UU1hHrbHNw5_2dAuh____15).
diagram_fact(synonym, cell_73, id_N7UU1hHrbHNw5_2dAuh____16).
diagram_fact(synonym, cell_74, id_N7UU1hHrbHNw5_2dAuh____18).
diagram_fact(synonym, cell_75, id_N7UU1hHrbHNw5_2dAuh____19).
diagram_fact(synonym, cell_76, id_N7UU1hHrbHNw5_2dAuh____58).
diagram_fact(synonym, cell_77, id_N7UU1hHrbHNw5_2dAuh____20).
diagram_fact(synonym, cell_78, id_N7UU1hHrbHNw5_2dAuh____21).
diagram_fact(synonym, cell_79, id_N7UU1hHrbHNw5_2dAuh____22).
diagram_fact(synonym, cell_8, i5jZ3dy8F4nkPbaXPHF6__2).
diagram_fact(synonym, cell_80, id_N7UU1hHrbHNw5_2dAuh____23).
diagram_fact(synonym, cell_81, id_N7UU1hHrbHNw5_2dAuh____24).
diagram_fact(synonym, cell_82, id_N7UU1hHrbHNw5_2dAuh____25).
diagram_fact(synonym, cell_83, id_N7UU1hHrbHNw5_2dAuh____26).
diagram_fact(synonym, cell_84, id_N7UU1hHrbHNw5_2dAuh____27).
diagram_fact(synonym, cell_85, id_N7UU1hHrbHNw5_2dAuh____28).
diagram_fact(synonym, cell_86, id_N7UU1hHrbHNw5_2dAuh____57).
diagram_fact(synonym, cell_87, id_N7UU1hHrbHNw5_2dAuh____29).
diagram_fact(synonym, cell_88, id_N7UU1hHrbHNw5_2dAuh____30).
diagram_fact(synonym, cell_89, id_N7UU1hHrbHNw5_2dAuh____31).
diagram_fact(synonym, cell_9, i5jZ3dy8F4nkPbaXPHF6__3).
diagram_fact(synonym, cell_90, id_N7UU1hHrbHNw5_2dAuh____32).
diagram_fact(synonym, cell_91, id_N7UU1hHrbHNw5_2dAuh____63).
diagram_fact(synonym, cell_92, id_N7UU1hHrbHNw5_2dAuh____33).
diagram_fact(synonym, cell_93, id_N7UU1hHrbHNw5_2dAuh____34).
diagram_fact(synonym, cell_94, id_N7UU1hHrbHNw5_2dAuh____38).
diagram_fact(synonym, cell_95, id_N7UU1hHrbHNw5_2dAuh____39).
diagram_fact(synonym, cell_96, id_N7UU1hHrbHNw5_2dAuh____56).
diagram_fact(synonym, cell_97, id_N7UU1hHrbHNw5_2dAuh____40).
diagram_fact(synonym, cell_98, id_N7UU1hHrbHNw5_2dAuh____41).
diagram_fact(synonym, cell_99, id_N7UU1hHrbHNw5_2dAuh____42).
diagram_fact(target, cell_10, aPelzSQw_j5YxlEaLFGD__39).
diagram_fact(target, cell_101, id_N7UU1hHrbHNw5_2dAuh____50).
diagram_fact(target, cell_106, id_N7UU1hHrbHNw5_2dAuh____54).
diagram_fact(target, cell_111, id_9_2W__ZNaL5BkT9HVN__QL__8).
diagram_fact(target, cell_15, aPelzSQw_j5YxlEaLFGD__46).
diagram_fact(target, cell_19, aPelzSQw_j5YxlEaLFGD__50).
diagram_fact(target, cell_24, aPelzSQw_j5YxlEaLFGD__55).
diagram_fact(target, cell_29, aPelzSQw_j5YxlEaLFGD__71).
diagram_fact(target, cell_34, aPelzSQw_j5YxlEaLFGD__76).
diagram_fact(target, cell_42, id_Eg2JflB1LH7_nM4HlBUV__2).
diagram_fact(target, cell_44, id_N7UU1hHrbHNw5_2dAuh____4).
diagram_fact(target, cell_52, id_IZh1Ggwe__xGZHwZ9__CIt__4).
diagram_fact(target, cell_56, id_N7UU1hHrbHNw5_2dAuh____8).
diagram_fact(target, cell_61, id_N7UU1hHrbHNw5_2dAuh____12).
diagram_fact(target, cell_66, id_N7UU1hHrbHNw5_2dAuh____16).
diagram_fact(target, cell_71, id_N7UU1hHrbHNw5_2dAuh____21).
diagram_fact(target, cell_76, id_N7UU1hHrbHNw5_2dAuh____26).
diagram_fact(target, cell_81, id_N7UU1hHrbHNw5_2dAuh____30).
diagram_fact(target, cell_86, id_N7UU1hHrbHNw5_2dAuh____34).
diagram_fact(target, cell_91, id_N7UU1hHrbHNw5_2dAuh____41).
diagram_fact(target, cell_96, id_N7UU1hHrbHNw5_2dAuh____46).
diagram_fact(value, cell_100, "var x = sfsynccode (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_102, "out").
diagram_fact(value, cell_103, "in").
diagram_fact(value, cell_104, "connections").
diagram_fact(value, cell_105, "var x = sfconnections (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_107, "out").
diagram_fact(value, cell_108, "in").
diagram_fact(value, cell_109, "design rule edge containment").
diagram_fact(value, cell_11, "out").
diagram_fact(value, cell_110, "var x = sfdesignruleedgecontainment (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_112, "out").
diagram_fact(value, cell_113, "in").
diagram_fact(value, cell_12, "in").
diagram_fact(value, cell_13, "diagramparser").
diagram_fact(value, cell_14, "var x = sfdiagramparser (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_16, "out").
diagram_fact(value, cell_17, "in").
diagram_fact(value, cell_18, "var x = sfstyleexpander (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_20, "out").
diagram_fact(value, cell_21, "in").
diagram_fact(value, cell_22, "asfactbase").
diagram_fact(value, cell_23, "var x = sfasfactbase (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_25, "out").
diagram_fact(value, cell_26, "in").
diagram_fact(value, cell_27, "deleteblanklines").
diagram_fact(value, cell_28, "var x = sfdeleteblanklines (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_30, "out").
diagram_fact(value, cell_31, "in").
diagram_fact(value, cell_32, "sortForPROLOG").
diagram_fact(value, cell_33, "var x = sfsortForPROLOG (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_35, "out").
diagram_fact(value, cell_36, "in").
diagram_fact(value, cell_37, "deleteTrailingSugar").
diagram_fact(value, cell_38, "var x = sfdeleteTrailingSugar (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_39, "in").
diagram_fact(value, cell_40, "kickStart").
diagram_fact(value, cell_41, "var rawbinary = sfreadfile (argv._[0]);&lt;br&gt;me.send (&quot;out&quot;, rawbinary, null);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_43, "out").
diagram_fact(value, cell_45, "out").
diagram_fact(value, cell_46, "prolog convert to json").
diagram_fact(value, cell_47, "var x = sfprolog2json (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_48, "in").
diagram_fact(value, cell_49, "finish").
diagram_fact(value, cell_50, "console.log (message.data);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_51, "in").
diagram_fact(value, cell_53, "out").
diagram_fact(value, cell_54, "kinds").
diagram_fact(value, cell_55, "var x = sfkinds (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_57, "out").
diagram_fact(value, cell_58, "in").
diagram_fact(value, cell_59, "name").
diagram_fact(value, cell_6, "das2f").
diagram_fact(value, cell_60, "var x = sfnames (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_62, "out").
diagram_fact(value, cell_63, "in").
diagram_fact(value, cell_64, "color").
diagram_fact(value, cell_65, "var x = sfcolor (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_67, "out").
diagram_fact(value, cell_68, "in").
diagram_fact(value, cell_69, "boundingbox").
diagram_fact(value, cell_7, "styleexpander").
diagram_fact(value, cell_70, "var x = sfboundingbox (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_72, "out").
diagram_fact(value, cell_73, "in").
diagram_fact(value, cell_74, "direction").
diagram_fact(value, cell_75, "var x = sfdirection (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_77, "out").
diagram_fact(value, cell_78, "in").
diagram_fact(value, cell_79, "contains").
diagram_fact(value, cell_8, "uncompress").
diagram_fact(value, cell_80, "var x = sfcontains (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_82, "out").
diagram_fact(value, cell_83, "in").
diagram_fact(value, cell_84, "contains port").
diagram_fact(value, cell_85, "var x = sfcontainsport (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_87, "out").
diagram_fact(value, cell_88, "in").
diagram_fact(value, cell_89, "direct containment").
diagram_fact(value, cell_9, "var u = sfuncompress (message.data);&lt;br&gt;me.send (&quot;out&quot;, u, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_90, "var x = sfdirectcontainment (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_92, "out").
diagram_fact(value, cell_93, "in").
diagram_fact(value, cell_94, "edge containment").
diagram_fact(value, cell_95, "var x = sfedgecontainment (message.data);&lt;br&gt;me.send (&quot;out&quot;, x, message);&lt;br&gt;&lt;div&gt;&lt;/div&gt;").
diagram_fact(value, cell_97, "out").
diagram_fact(value, cell_98, "in").
diagram_fact(value, cell_99, "sync code").
diagram_fact(vertex, cell_100, 1).
diagram_fact(vertex, cell_102, 1).
diagram_fact(vertex, cell_103, 1).
diagram_fact(vertex, cell_104, 1).
diagram_fact(vertex, cell_105, 1).
diagram_fact(vertex, cell_107, 1).
diagram_fact(vertex, cell_108, 1).
diagram_fact(vertex, cell_109, 1).
diagram_fact(vertex, cell_11, 1).
diagram_fact(vertex, cell_110, 1).
diagram_fact(vertex, cell_112, 1).
diagram_fact(vertex, cell_113, 1).
diagram_fact(vertex, cell_12, 1).
diagram_fact(vertex, cell_13, 1).
diagram_fact(vertex, cell_14, 1).
diagram_fact(vertex, cell_16, 1).
diagram_fact(vertex, cell_17, 1).
diagram_fact(vertex, cell_18, 1).
diagram_fact(vertex, cell_20, 1).
diagram_fact(vertex, cell_21, 1).
diagram_fact(vertex, cell_22, 1).
diagram_fact(vertex, cell_23, 1).
diagram_fact(vertex, cell_25, 1).
diagram_fact(vertex, cell_26, 1).
diagram_fact(vertex, cell_27, 1).
diagram_fact(vertex, cell_28, 1).
diagram_fact(vertex, cell_30, 1).
diagram_fact(vertex, cell_31, 1).
diagram_fact(vertex, cell_32, 1).
diagram_fact(vertex, cell_33, 1).
diagram_fact(vertex, cell_35, 1).
diagram_fact(vertex, cell_36, 1).
diagram_fact(vertex, cell_37, 1).
diagram_fact(vertex, cell_38, 1).
diagram_fact(vertex, cell_39, 1).
diagram_fact(vertex, cell_40, 1).
diagram_fact(vertex, cell_41, 1).
diagram_fact(vertex, cell_43, 1).
diagram_fact(vertex, cell_45, 1).
diagram_fact(vertex, cell_46, 1).
diagram_fact(vertex, cell_47, 1).
diagram_fact(vertex, cell_48, 1).
diagram_fact(vertex, cell_49, 1).
diagram_fact(vertex, cell_50, 1).
diagram_fact(vertex, cell_51, 1).
diagram_fact(vertex, cell_53, 1).
diagram_fact(vertex, cell_54, 1).
diagram_fact(vertex, cell_55, 1).
diagram_fact(vertex, cell_57, 1).
diagram_fact(vertex, cell_58, 1).
diagram_fact(vertex, cell_59, 1).
diagram_fact(vertex, cell_6, 1).
diagram_fact(vertex, cell_60, 1).
diagram_fact(vertex, cell_62, 1).
diagram_fact(vertex, cell_63, 1).
diagram_fact(vertex, cell_64, 1).
diagram_fact(vertex, cell_65, 1).
diagram_fact(vertex, cell_67, 1).
diagram_fact(vertex, cell_68, 1).
diagram_fact(vertex, cell_69, 1).
diagram_fact(vertex, cell_7, 1).
diagram_fact(vertex, cell_70, 1).
diagram_fact(vertex, cell_72, 1).
diagram_fact(vertex, cell_73, 1).
diagram_fact(vertex, cell_74, 1).
diagram_fact(vertex, cell_75, 1).
diagram_fact(vertex, cell_77, 1).
diagram_fact(vertex, cell_78, 1).
diagram_fact(vertex, cell_79, 1).
diagram_fact(vertex, cell_8, 1).
diagram_fact(vertex, cell_80, 1).
diagram_fact(vertex, cell_82, 1).
diagram_fact(vertex, cell_83, 1).
diagram_fact(vertex, cell_84, 1).
diagram_fact(vertex, cell_85, 1).
diagram_fact(vertex, cell_87, 1).
diagram_fact(vertex, cell_88, 1).
diagram_fact(vertex, cell_89, 1).
diagram_fact(vertex, cell_9, 1).
diagram_fact(vertex, cell_90, 1).
diagram_fact(vertex, cell_92, 1).
diagram_fact(vertex, cell_93, 1).
diagram_fact(vertex, cell_94, 1).
diagram_fact(vertex, cell_95, 1).
diagram_fact(vertex, cell_97, 1).
diagram_fact(vertex, cell_98, 1).
diagram_fact(vertex, cell_99, 1).
diagram_fact(verticalAlign, cell_104, "top").
diagram_fact(verticalAlign, cell_109, "top").
diagram_fact(verticalAlign, cell_13, "top").
diagram_fact(verticalAlign, cell_22, "top").
diagram_fact(verticalAlign, cell_27, "top").
diagram_fact(verticalAlign, cell_32, "top").
diagram_fact(verticalAlign, cell_37, "top").
diagram_fact(verticalAlign, cell_40, "top").
diagram_fact(verticalAlign, cell_46, "top").
diagram_fact(verticalAlign, cell_49, "top").
diagram_fact(verticalAlign, cell_54, "top").
diagram_fact(verticalAlign, cell_59, "top").
diagram_fact(verticalAlign, cell_6, "top").
diagram_fact(verticalAlign, cell_64, "top").
diagram_fact(verticalAlign, cell_69, "top").
diagram_fact(verticalAlign, cell_7, "top").
diagram_fact(verticalAlign, cell_74, "top").
diagram_fact(verticalAlign, cell_79, "top").
diagram_fact(verticalAlign, cell_8, "top").
diagram_fact(verticalAlign, cell_84, "top").
diagram_fact(verticalAlign, cell_89, "top").
diagram_fact(verticalAlign, cell_94, "top").
diagram_fact(verticalAlign, cell_99, "top").
diagram_fact(whiteSpace, cell_100, "wrap").
diagram_fact(whiteSpace, cell_102, "wrap").
diagram_fact(whiteSpace, cell_103, "wrap").
diagram_fact(whiteSpace, cell_104, "wrap").
diagram_fact(whiteSpace, cell_105, "wrap").
diagram_fact(whiteSpace, cell_107, "wrap").
diagram_fact(whiteSpace, cell_108, "wrap").
diagram_fact(whiteSpace, cell_109, "wrap").
diagram_fact(whiteSpace, cell_11, "wrap").
diagram_fact(whiteSpace, cell_110, "wrap").
diagram_fact(whiteSpace, cell_112, "wrap").
diagram_fact(whiteSpace, cell_113, "wrap").
diagram_fact(whiteSpace, cell_12, "wrap").
diagram_fact(whiteSpace, cell_13, "wrap").
diagram_fact(whiteSpace, cell_14, "wrap").
diagram_fact(whiteSpace, cell_16, "wrap").
diagram_fact(whiteSpace, cell_17, "wrap").
diagram_fact(whiteSpace, cell_18, "wrap").
diagram_fact(whiteSpace, cell_20, "wrap").
diagram_fact(whiteSpace, cell_21, "wrap").
diagram_fact(whiteSpace, cell_22, "wrap").
diagram_fact(whiteSpace, cell_23, "wrap").
diagram_fact(whiteSpace, cell_25, "wrap").
diagram_fact(whiteSpace, cell_26, "wrap").
diagram_fact(whiteSpace, cell_27, "wrap").
diagram_fact(whiteSpace, cell_28, "wrap").
diagram_fact(whiteSpace, cell_30, "wrap").
diagram_fact(whiteSpace, cell_31, "wrap").
diagram_fact(whiteSpace, cell_32, "wrap").
diagram_fact(whiteSpace, cell_33, "wrap").
diagram_fact(whiteSpace, cell_35, "wrap").
diagram_fact(whiteSpace, cell_36, "wrap").
diagram_fact(whiteSpace, cell_37, "wrap").
diagram_fact(whiteSpace, cell_38, "wrap").
diagram_fact(whiteSpace, cell_39, "wrap").
diagram_fact(whiteSpace, cell_40, "wrap").
diagram_fact(whiteSpace, cell_41, "wrap").
diagram_fact(whiteSpace, cell_43, "wrap").
diagram_fact(whiteSpace, cell_45, "wrap").
diagram_fact(whiteSpace, cell_46, "wrap").
diagram_fact(whiteSpace, cell_47, "wrap").
diagram_fact(whiteSpace, cell_48, "wrap").
diagram_fact(whiteSpace, cell_49, "wrap").
diagram_fact(whiteSpace, cell_50, "wrap").
diagram_fact(whiteSpace, cell_51, "wrap").
diagram_fact(whiteSpace, cell_53, "wrap").
diagram_fact(whiteSpace, cell_54, "wrap").
diagram_fact(whiteSpace, cell_55, "wrap").
diagram_fact(whiteSpace, cell_57, "wrap").
diagram_fact(whiteSpace, cell_58, "wrap").
diagram_fact(whiteSpace, cell_59, "wrap").
diagram_fact(whiteSpace, cell_6, "wrap").
diagram_fact(whiteSpace, cell_60, "wrap").
diagram_fact(whiteSpace, cell_62, "wrap").
diagram_fact(whiteSpace, cell_63, "wrap").
diagram_fact(whiteSpace, cell_64, "wrap").
diagram_fact(whiteSpace, cell_65, "wrap").
diagram_fact(whiteSpace, cell_67, "wrap").
diagram_fact(whiteSpace, cell_68, "wrap").
diagram_fact(whiteSpace, cell_69, "wrap").
diagram_fact(whiteSpace, cell_7, "wrap").
diagram_fact(whiteSpace, cell_70, "wrap").
diagram_fact(whiteSpace, cell_72, "wrap").
diagram_fact(whiteSpace, cell_73, "wrap").
diagram_fact(whiteSpace, cell_74, "wrap").
diagram_fact(whiteSpace, cell_75, "wrap").
diagram_fact(whiteSpace, cell_77, "wrap").
diagram_fact(whiteSpace, cell_78, "wrap").
diagram_fact(whiteSpace, cell_79, "wrap").
diagram_fact(whiteSpace, cell_8, "wrap").
diagram_fact(whiteSpace, cell_80, "wrap").
diagram_fact(whiteSpace, cell_82, "wrap").
diagram_fact(whiteSpace, cell_83, "wrap").
diagram_fact(whiteSpace, cell_84, "wrap").
diagram_fact(whiteSpace, cell_85, "wrap").
diagram_fact(whiteSpace, cell_87, "wrap").
diagram_fact(whiteSpace, cell_88, "wrap").
diagram_fact(whiteSpace, cell_89, "wrap").
diagram_fact(whiteSpace, cell_9, "wrap").
diagram_fact(whiteSpace, cell_90, "wrap").
diagram_fact(whiteSpace, cell_92, "wrap").
diagram_fact(whiteSpace, cell_93, "wrap").
diagram_fact(whiteSpace, cell_94, "wrap").
diagram_fact(whiteSpace, cell_95, "wrap").
diagram_fact(whiteSpace, cell_97, "wrap").
diagram_fact(whiteSpace, cell_98, "wrap").
diagram_fact(whiteSpace, cell_99, "wrap").
diagram_fact(width, cell_100, 200).
diagram_fact(width, cell_102, 40).
diagram_fact(width, cell_103, 40).
diagram_fact(width, cell_104, 260).
diagram_fact(width, cell_105, 200).
diagram_fact(width, cell_107, 40).
diagram_fact(width, cell_108, 40).
diagram_fact(width, cell_109, 260).
diagram_fact(width, cell_11, 40).
diagram_fact(width, cell_110, 200).
diagram_fact(width, cell_112, 40).
diagram_fact(width, cell_113, 40).
diagram_fact(width, cell_12, 40).
diagram_fact(width, cell_13, 260).
diagram_fact(width, cell_14, 200).
diagram_fact(width, cell_16, 40).
diagram_fact(width, cell_17, 40).
diagram_fact(width, cell_18, 200).
diagram_fact(width, cell_20, 40).
diagram_fact(width, cell_21, 40).
diagram_fact(width, cell_22, 260).
diagram_fact(width, cell_23, 200).
diagram_fact(width, cell_25, 40).
diagram_fact(width, cell_26, 40).
diagram_fact(width, cell_27, 270).
diagram_fact(width, cell_28, 210).
diagram_fact(width, cell_30, 40).
diagram_fact(width, cell_31, 40).
diagram_fact(width, cell_32, 270).
diagram_fact(width, cell_33, 210).
diagram_fact(width, cell_35, 40).
diagram_fact(width, cell_36, 40).
diagram_fact(width, cell_37, 285).
diagram_fact(width, cell_38, 225).
diagram_fact(width, cell_39, 40).
diagram_fact(width, cell_40, 260).
diagram_fact(width, cell_41, 200).
diagram_fact(width, cell_43, 40).
diagram_fact(width, cell_45, 40).
diagram_fact(width, cell_46, 375).
diagram_fact(width, cell_47, 305).
diagram_fact(width, cell_48, 40).
diagram_fact(width, cell_49, 285).
diagram_fact(width, cell_50, 225).
diagram_fact(width, cell_51, 40).
diagram_fact(width, cell_53, 40).
diagram_fact(width, cell_54, 260).
diagram_fact(width, cell_55, 200).
diagram_fact(width, cell_57, 40).
diagram_fact(width, cell_58, 40).
diagram_fact(width, cell_59, 260).
diagram_fact(width, cell_6, 920).
diagram_fact(width, cell_60, 200).
diagram_fact(width, cell_62, 40).
diagram_fact(width, cell_63, 40).
diagram_fact(width, cell_64, 260).
diagram_fact(width, cell_65, 200).
diagram_fact(width, cell_67, 40).
diagram_fact(width, cell_68, 40).
diagram_fact(width, cell_69, 260).
diagram_fact(width, cell_7, 260).
diagram_fact(width, cell_70, 200).
diagram_fact(width, cell_72, 40).
diagram_fact(width, cell_73, 40).
diagram_fact(width, cell_74, 260).
diagram_fact(width, cell_75, 200).
diagram_fact(width, cell_77, 40).
diagram_fact(width, cell_78, 40).
diagram_fact(width, cell_79, 260).
diagram_fact(width, cell_8, 260).
diagram_fact(width, cell_80, 200).
diagram_fact(width, cell_82, 40).
diagram_fact(width, cell_83, 40).
diagram_fact(width, cell_84, 260).
diagram_fact(width, cell_85, 200).
diagram_fact(width, cell_87, 40).
diagram_fact(width, cell_88, 40).
diagram_fact(width, cell_89, 260).
diagram_fact(width, cell_9, 200).
diagram_fact(width, cell_90, 200).
diagram_fact(width, cell_92, 40).
diagram_fact(width, cell_93, 40).
diagram_fact(width, cell_94, 260).
diagram_fact(width, cell_95, 200).
diagram_fact(width, cell_97, 40).
diagram_fact(width, cell_98, 40).
diagram_fact(width, cell_99, 260).
diagram_fact(x, cell_100, 670).
diagram_fact(x, cell_102, 880).
diagram_fact(x, cell_103, 620).
diagram_fact(x, cell_104, 240).
diagram_fact(x, cell_105, 270).
diagram_fact(x, cell_107, 480).
diagram_fact(x, cell_108, 220).
diagram_fact(x, cell_109, 640).
diagram_fact(x, cell_11, 450).
diagram_fact(x, cell_110, 670).
diagram_fact(x, cell_112, 880).
diagram_fact(x, cell_113, 620).
diagram_fact(x, cell_12, 190).
diagram_fact(x, cell_13, 570).
diagram_fact(x, cell_14, 600).
diagram_fact(x, cell_16, 810).
diagram_fact(x, cell_17, 550).
diagram_fact(x, cell_18, 250).
diagram_fact(x, cell_20, 460).
diagram_fact(x, cell_21, 200).
diagram_fact(x, cell_22, 580).
diagram_fact(x, cell_23, 610).
diagram_fact(x, cell_25, 820).
diagram_fact(x, cell_26, 560).
diagram_fact(x, cell_27, 230).
diagram_fact(x, cell_28, 260).
diagram_fact(x, cell_30, 480).
diagram_fact(x, cell_31, 210).
diagram_fact(x, cell_32, 230).
diagram_fact(x, cell_33, 260).
diagram_fact(x, cell_35, 480).
diagram_fact(x, cell_36, 210).
diagram_fact(x, cell_37, 575).
diagram_fact(x, cell_38, 605).
diagram_fact(x, cell_39, 555).
diagram_fact(x, cell_40, 200).
diagram_fact(x, cell_41, 230).
diagram_fact(x, cell_43, 440).
diagram_fact(x, cell_45, 840).
diagram_fact(x, cell_46, 400).
diagram_fact(x, cell_47, 430).
diagram_fact(x, cell_48, 380).
diagram_fact(x, cell_49, 437.5).
diagram_fact(x, cell_50, 467.5).
diagram_fact(x, cell_51, 417.5).
diagram_fact(x, cell_53, 755).
diagram_fact(x, cell_54, 240).
diagram_fact(x, cell_55, 270).
diagram_fact(x, cell_57, 480).
diagram_fact(x, cell_58, 220).
diagram_fact(x, cell_59, 640).
diagram_fact(x, cell_6, 100).
diagram_fact(x, cell_60, 670).
diagram_fact(x, cell_62, 880).
diagram_fact(x, cell_63, 620).
diagram_fact(x, cell_64, 240).
diagram_fact(x, cell_65, 270).
diagram_fact(x, cell_67, 480).
diagram_fact(x, cell_68, 220).
diagram_fact(x, cell_69, 640).
diagram_fact(x, cell_7, 220).
diagram_fact(x, cell_70, 670).
diagram_fact(x, cell_72, 880).
diagram_fact(x, cell_73, 620).
diagram_fact(x, cell_74, 240).
diagram_fact(x, cell_75, 270).
diagram_fact(x, cell_77, 480).
diagram_fact(x, cell_78, 220).
diagram_fact(x, cell_79, 640).
diagram_fact(x, cell_8, 210).
diagram_fact(x, cell_80, 670).
diagram_fact(x, cell_82, 880).
diagram_fact(x, cell_83, 620).
diagram_fact(x, cell_84, 240).
diagram_fact(x, cell_85, 270).
diagram_fact(x, cell_87, 480).
diagram_fact(x, cell_88, 220).
diagram_fact(x, cell_89, 640).
diagram_fact(x, cell_9, 240).
diagram_fact(x, cell_90, 670).
diagram_fact(x, cell_92, 880).
diagram_fact(x, cell_93, 620).
diagram_fact(x, cell_94, 240).
diagram_fact(x, cell_95, 270).
diagram_fact(x, cell_97, 480).
diagram_fact(x, cell_98, 220).
diagram_fact(x, cell_99, 640).
diagram_fact(y, cell_100, 2645).
diagram_fact(y, cell_102, 2645).
diagram_fact(y, cell_103, 2645).
diagram_fact(y, cell_104, 2840).
diagram_fact(y, cell_105, 2885).
diagram_fact(y, cell_107, 2885).
diagram_fact(y, cell_108, 2885).
diagram_fact(y, cell_109, 2840).
diagram_fact(y, cell_11, 385).
diagram_fact(y, cell_110, 2885).
diagram_fact(y, cell_112, 2885).
diagram_fact(y, cell_113, 2885).
diagram_fact(y, cell_12, 385).
diagram_fact(y, cell_13, 340).
diagram_fact(y, cell_14, 385).
diagram_fact(y, cell_16, 385).
diagram_fact(y, cell_17, 385).
diagram_fact(y, cell_18, 615).
diagram_fact(y, cell_20, 615).
diagram_fact(y, cell_21, 615).
diagram_fact(y, cell_22, 570).
diagram_fact(y, cell_23, 615).
diagram_fact(y, cell_25, 615).
diagram_fact(y, cell_26, 615).
diagram_fact(y, cell_27, 770).
diagram_fact(y, cell_28, 815).
diagram_fact(y, cell_30, 815).
diagram_fact(y, cell_31, 815).
diagram_fact(y, cell_32, 960).
diagram_fact(y, cell_33, 1005).
diagram_fact(y, cell_35, 1005).
diagram_fact(y, cell_36, 1005).
diagram_fact(y, cell_37, 962.5).
diagram_fact(y, cell_38, 1007.5).
diagram_fact(y, cell_39, 1007.5).
diagram_fact(y, cell_40, 130).
diagram_fact(y, cell_41, 175).
diagram_fact(y, cell_43, 175).
diagram_fact(y, cell_45, 1010).
diagram_fact(y, cell_46, 3080).
diagram_fact(y, cell_47, 3125).
diagram_fact(y, cell_48, 3125).
diagram_fact(y, cell_49, 3320).
diagram_fact(y, cell_50, 3365).
diagram_fact(y, cell_51, 3365).
diagram_fact(y, cell_53, 3125).
diagram_fact(y, cell_54, 1640).
diagram_fact(y, cell_55, 1685).
diagram_fact(y, cell_57, 1685).
diagram_fact(y, cell_58, 1685).
diagram_fact(y, cell_59, 1640).
diagram_fact(y, cell_6, 70).
diagram_fact(y, cell_60, 1685).
diagram_fact(y, cell_62, 1685).
diagram_fact(y, cell_63, 1685).
diagram_fact(y, cell_64, 1880).
diagram_fact(y, cell_65, 1925).
diagram_fact(y, cell_67, 1925).
diagram_fact(y, cell_68, 1925).
diagram_fact(y, cell_69, 1880).
diagram_fact(y, cell_7, 570).
diagram_fact(y, cell_70, 1925).
diagram_fact(y, cell_72, 1925).
diagram_fact(y, cell_73, 1925).
diagram_fact(y, cell_74, 2120).
diagram_fact(y, cell_75, 2165).
diagram_fact(y, cell_77, 2165).
diagram_fact(y, cell_78, 2165).
diagram_fact(y, cell_79, 2120).
diagram_fact(y, cell_8, 340).
diagram_fact(y, cell_80, 2165).
diagram_fact(y, cell_82, 2165).
diagram_fact(y, cell_83, 2165).
diagram_fact(y, cell_84, 2360).
diagram_fact(y, cell_85, 2405).
diagram_fact(y, cell_87, 2405).
diagram_fact(y, cell_88, 2405).
diagram_fact(y, cell_89, 2360).
diagram_fact(y, cell_9, 385).
diagram_fact(y, cell_90, 2405).
diagram_fact(y, cell_92, 2405).
diagram_fact(y, cell_93, 2405).
diagram_fact(y, cell_94, 2600).
diagram_fact(y, cell_95, 2645).
diagram_fact(y, cell_97, 2645).
diagram_fact(y, cell_98, 2645).
diagram_fact(y, cell_99, 2600).